service:
  host: "0.0.0.0"
  port: 8000

services:
  collector_url: "http://collector:5000"
  ml_service_url: "http://ml_service:5000"
  storage_url: "http://storage:5000"

logging:
  log_file: "./web_master.log"